name: Test Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: orangehrm
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r automation/requirements.txt
        pip install pytest pytest-xdist
        
    - name: Run tests
      run: |
        cd automation
        pytest -n auto --html=report.html --self-contained-html
        
    - name: Upload test report
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-report
        path: automation/report.html
